[package]
edition = "2021"
name = "flavors_clap"
version = "0.1.0"

[dependencies]
linearf = { path = "../../lnf/model/core" }
filter = { git = "https://github.com/liuchengxu/vim-clap", rev = "6fd4feca", default-features = false }
futures = "^0.3"
serde = "^1"
